# Generated by Django 4.0.1 on 2022-03-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='win',
            new_name='wins',
        ),
    ]
